# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='BENCH',
            field=models.CharField(default=b'[]', max_length=15),
        ),
        migrations.AddField(
            model_name='roster',
            name='DEF1',
            field=models.CharField(default=b'noplayer', max_length=15),
        ),
        migrations.AddField(
            model_name='roster',
            name='FLEX1',
            field=models.CharField(default=b'noplayer', max_length=15),
        ),
        migrations.AddField(
            model_name='roster',
            name='FLEX2',
            field=models.CharField(default=b'noplayer', max_length=15),
        ),
        migrations.AddField(
            model_name='roster',
            name='FLEX3',
            field=models.CharField(default=b'noplayer', max_length=15),
        ),
        migrations.AddField(
            model_name='roster',
            name='K1',
            field=models.CharField(default=b'noplayer', max_length=15),
        ),
        migrations.AddField(
            model_name='roster',
            name='QB1',
            field=models.CharField(default=b'noplayer', max_length=15),
        ),
        migrations.AddField(
            model_name='roster',
            name='QB2',
            field=models.CharField(default=b'noplayer', max_length=15),
        ),
        migrations.AddField(
            model_name='roster',
            name='RB1',
            field=models.CharField(default=b'noplayer', max_length=15),
        ),
        migrations.AddField(
            model_name='roster',
            name='RB2',
            field=models.CharField(default=b'noplayer', max_length=15),
        ),
        migrations.AddField(
            model_name='roster',
            name='TE1',
            field=models.CharField(default=b'noplayer', max_length=15),
        ),
        migrations.AddField(
            model_name='roster',
            name='WR1',
            field=models.CharField(default=b'noplayer', max_length=15),
        ),
        migrations.AddField(
            model_name='roster',
            name='WR2',
            field=models.CharField(default=b'noplayer', max_length=15),
        ),
        migrations.AddField(
            model_name='team',
            name='championships',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.CharField(default=b'Team-0', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default=b'Insert Team Name Here', max_length=30),
        ),
        migrations.AddField(
            model_name='team',
            name='team_owner',
            field=models.CharField(default=b'noowner', max_length=30),
        ),
    ]
