# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170109_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(default=0)),
                ('home_team', models.CharField(default=b'Team-0', max_length=10)),
                ('away_team', models.CharField(default=b'Team-0', max_length=10)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Playoffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playoff_teams', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(default=b'Division Name here', max_length=20)),
                ('number_of_teams', models.IntegerField(default=1)),
                ('playoff_teams', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('year', models.IntegerField(default=0)),
                ('number_of_weeks', models.IntegerField(default=1)),
                ('playoffs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Playoffs')),
            ],
        ),
        migrations.AddField(
            model_name='standings',
            name='parent_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Schedule'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='parent_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Schedule'),
        ),
    ]
