# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170116_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ng_id', models.CharField(default=b'noplayer', max_length=30)),
                ('esb_id', models.CharField(default=b'', max_length=30)),
                ('team', models.CharField(default=b'UNK', max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='roster',
        ),
        migrations.AddField(
            model_name='roster',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roster',
            name='FLEX1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FLEX1', to='base.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='FLEX2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FLEX2', to='base.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='FLEX3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FLEX3', to='base.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='K1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='K1', to='base.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='QB1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QB1', to='base.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='QB2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QB2', to='base.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='RB1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RB1', to='base.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='RB2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RB2', to='base.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='TE1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TE1', to='base.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='WR1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WR1', to='base.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='WR2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WR2', to='base.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='fantasy_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Team'),
        ),
    ]
