# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20170123_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(default=b'Free Agent', max_length=15),
        ),
    ]
