# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_fantasypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasypoints',
            name='total',
            field=models.FloatField(default=None, null=True),
        ),
    ]
