# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_fantasypoints_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_players', models.CharField(max_length=1000)),
                ('rec_players', models.CharField(max_length=1000)),
                ('accepted_date', models.DateTimeField()),
                ('process_date', models.DateTimeField()),
                ('proposing_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PropTeam', to='base.Team')),
                ('receiving_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecTeam', to='base.Team')),
            ],
        ),
        migrations.AddField(
            model_name='standings',
            name='archive',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AddField(
            model_name='standings',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roster',
            name='DEF1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DEF1', to='base.Player'),
        ),
    ]
