class POSITIONS:
    QUARTERBACK = "QB"
    RUNNING_BACK = "RB"
    WIDE_RECEIVER = "WR"
    TIGHT_END = "TE"
    FLEX = "FLEX"
    KICKER = "K"
    DEFENCE = "DEF"
    BENCH = "BEN"


class TEAM_CONST:

    STARTER_ORDER = [POSITIONS.QUARTERBACK, POSITIONS.RUNNING_BACK,
                     POSITIONS.WIDE_RECEIVER, POSITIONS.TIGHT_END,
                     POSITIONS.FLEX, POSITIONS.KICKER, POSITIONS.DEFENCE,
                     POSITIONS.BENCH]

    POSITION_ACCEPTS = {
        POSITIONS.QUARTERBACK: [POSITIONS.QUARTERBACK],
        POSITIONS.RUNNING_BACK: [POSITIONS.RUNNING_BACK],
        POSITIONS.WIDE_RECEIVER: [POSITIONS.WIDE_RECEIVER],
        POSITIONS.TIGHT_END: [POSITIONS.TIGHT_END],
        POSITIONS.FLEX: [POSITIONS.RUNNING_BACK,POSITIONS.WIDE_RECEIVER,POSITIONS.TIGHT_END],
        POSITIONS.KICKER: [POSITIONS.KICKER],
        POSITIONS.DEFENCE: [POSITIONS.DEFENCE],
        POSITIONS.BENCH: [POSITIONS.QUARTERBACK,POSITIONS.RUNNING_BACK,POSITIONS.WIDE_RECEIVER,POSITIONS.TIGHT_END,POSITIONS.KICKER,POSITIONS.DEFENCE]
    }

    STARTING_SPOTS = {
        POSITIONS.QUARTERBACK: 2,
        POSITIONS.RUNNING_BACK: 2,
        POSITIONS.WIDE_RECEIVER: 2,
        POSITIONS.TIGHT_END: 1,
        POSITIONS.FLEX: 3,
        POSITIONS.KICKER: 1,
        POSITIONS.DEFENCE: 1,
        POSITIONS.BENCH: 8
    }
